# Generated by Django 3.0.1 on 2019-12-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='datetime',
            field=models.DateTimeField(null=True, verbose_name='weather date / time'),
        ),
    ]
